FROM python:3.9
USER root
# https://docs.getdbt.com/dbt-cli/install/pip
RUN apt-get update
RUN pip install \
  dbt-core \
  dbt-postgres \
  dbt-redshift \
  dbt-snowflake \
  dbt-bigquery
RUN dbt --version
# keep the container alive after building
CMD tail -f /dev/null